### PR TITLE
cards to rows

### LINKED ISSUE #37: A table with frameworks as rows instead of cards?
As you want to benchmark many frameworks from many different languages, I expect that the number of frameworks is very high. Is it a better to have them list as rows of a table?

|Frameworks|Version|Approach|Language|Size(*)|Score(ms)|Notes|
|---|---|---|---|---|---|---|
|mogwai|0.2|?|Rust|?| ? ||
|react|?|vDOM|JS|?|?|error message|

(*) size of all files need to deliver to browser (in kB)

### PR DESCRIPTION
**Pull request by aclueless**
closes #37 

Sorry for unrelated changes because of `cargo fmt`

* I convert cards to table of rows
* Add a `Toggle All` checkbox to check/uncheck all frameworks. But it's not functional yet (I am not familiar with mogwai)
* Dropped `Solo` button: Can be replace by `Toggle All` and select one?
* Not fill `Size` and `Score` yet.

(If there is a `Solo` button, on clicking it, I expect it run the benchmark for the framework)

Here is a screenshot of the UI change

Screenshot_2020-04-23 todo-mvc-bench

### CODE REVIEW

**Comment by schell** [comment]
Great! I'll add the remaining functionality when I can, or you can keep hacking. What do you prefer?

**Comment by schell** [comment]
After this PR is merged I will reformat the whole project with some more "standard" rustfmt settings.

**Comment by aclueless** [comment]
> What do you prefer?

It depends. I don't have much spare time and learning mogwai is not my top priority, so it's faster if you add them.

**Comment by schell** [comment]
Sure thing. :+1:

**Comment by aclueless** [comment]
Hi, I added the functionality for the ToggleAll button (by looking and learning from `mogwai/examples/todomvc`). It works. But if you manually toggle a framework then click the ToggleAll, the framework that being manually toggle refuse to update to any new value. I think it's a bug in mogwai?

**Comment by schell** [comment]
@aclueless - sorry, I've been slammed at work. I'll check this out and fix your bug.

**Comment by schell** [comment]
K, I have the project building with no warnings now.

**Comment by schell** [comment]
It's not a bug in mogwai - it seems that a boolean attribute "checked" is not enough to toggle a checkbox once `set_checked` has been used (the equivalent javascript is `input.checked = trueOrFalse`. It's probably worth adding an impl for `Gizmo<HtmlInputElement>` that includes an `rx_checked` function for convenience but this PR fixes it without that (using a more general approach) https://github.com/aclueless/todo-mvc-bench/pull/1.

~~Merge the above PR into your changes an then I'll merge this PR.~~ Thanks!

**Pull request merged**
